#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumBribes function below.
def minimumBribes(q):
    bribe = 0
    for i in range(len(q)-1,-1,-1):
        if q[i]-(i+1)>2:
            print("Too chaotic")
            return
        for j in range(max(0,q[i]-2),i):
            if q[j]>q[i]:
                bribe+=1
    print(bribe)
    
 ###OR###   
    
def minimumBribes(q):
    bribe = 0
    swap = 0
    for i in range(len(q)-1,-1,-1):
        if q[i]-(i+1)>2:
            print("Too chaotic")
            return
    for i in range(len(q)-1):
        for j in range(len(q)-1):
            if q[j]>q[j+1]:
                q[j],q[j+1]=q[j+1],q[j]
                bribe+=1
                swap = 1
            
        if swap:
            swap = 0
        else:
            break
    print(bribe)             
                
if __name__ == '__main__':

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        q = list(map(int, input().rstrip().split()))

        minimumBribes(q)
