#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    count = s.count('a')
    if len(s)>=n:
        return s[:n].count('a')
    
    x,y = divmod(n,len(s))
    count = count*x
    add_s = s[:y]
    return count+add_s.count('a')
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
