#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the substrCount function below.
def substrCount(n, s):
   ans = 0
   samechar = [0]*n
   i=0
   while i<n:
        repeat = 1
        j=i+1
        while j<n:
            if s[i]!=s[j]:
                break
            repeat +=1
            j+=1
        ans+= int((repeat*(repeat+1))/2)
        samechar [i] = repeat
        i=j
   for j in range(1,n):
        if s[j]==s[j-1]:
            samechar[j]=samechar[j-1]
        if (j>0 and j<n-1) and s[j-1]==s[j+1] and s[j]!=s[j-1]:
            ans+=samechar[j-1] if samechar[j-1]<samechar[j+1] else samechar[j+1]
   return ans
            
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = substrCount(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
