#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the highestValuePalindrome function below.
def highestValuePalindrome(s, n, k):
    s = list(s)
    mark = [0]*n
    
    #Convert string into palindrome
    l = 0
    r = n-1
    while l<=r:
        if s[l]!=s[r]:
            if s[l]>s[r]:
                s[r]=s[l]
                mark[r]=1
            else:
                s[l]=s[r]
                mark[l]=1
            k-=1
        l+=1
        r-=1
    
    #Check if palindrome is under limit
    if k<0:
        return "-1"
    
    #Maximise the palindrome
    l=0
    r=n-1
    
    while l<=r:
        if l==r and k>=1:
            s[l]='9'
            break
        if s[l]<'9':
            #check for not touched previously
            if mark[l]==0 and mark[r]==0 and k>=2:
                s[l]=s[r]='9'
                k-=2
            #changed before
            if (mark[l]==1 or mark[r]==1) and k>=1:
                s[l]=s[r]='9'
                k-=1
        l+=1
        r-=1
    return "".join(s)
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    s = input()

    result = highestValuePalindrome(s, n, k)

    fptr.write(result + '\n')

    fptr.close()
